### ISSUE TITLE
Image uploading

### ISSUE THREAD

**Issue by vorvulev** [hoodiehq/faq#115]
Dear Hoodie developers!
Thx so much for you work!
But i can't undersand, how to upload some images on server for example. 
I'm coded with deployd, where i found a fileupload plugin.
Can you tell me how can i do that, or there is a upload plugin? 

Cheers, Дмитрий

**Comment by espy** [comment]
Hi there, 
the current version of Hoodie isn't really good for images, because it still uses localstorage to store a user's data in the browser, and that isn't a great place to put them. We're moving to using PouchDB instead, and that will then support binary attachments properly. 

It really depends whether you want all of the images a user uploads to be synced with their browser store. If not, best just upload them to somewhere else and store the URL in Hoodie. If you do need offline available, syncing images, you can:

* encode them as base64 and store them as strings in the current version of Hoodie. **But**: This will only work with few, small images, as localstorage is limited to 2.5–5MB, depending on browser and device. This is good enough for a logo or a small avatar, though
* use PouchDB in _parallel_ to Hoodie to store images
* wait for Hoodie to complete its migration to PouchDB, and then just use Hoodie

I'm sorry we don't have a clean solution for this yet, but we're nearly there!

Thanks for your interest :)

**Comment by vorvulev** [comment]
Thanks for advice :)
Good luck in the development!
