### ISSUE TITLE
does it scale up 

### ISSUE THREAD

**Issue by talavishay** [hoodiehq/faq#122]
is hoodie ready for production / does it scale up ?

**Comment by gr2m** [comment]
Hey @talavishay, thanks for your question :) I think others can give more detailed questions on this, but we run a Hoodie app in production with thousands of active users: https://minutes.io. And we didn’t run into scaling issues. Mostly because we use two things in the back-end that proved to scale very well: CouchDB & hapi.

And as you build offline-first app by default if you use Hoodie, there are some fantastic side effects:
1. People can use your app without even signing up. All data is stored locally and only synced once they create an account. Example: https://minutes.io/new/Meeting
2. If your server is down, people don’t even realise it, it’s just another reason for your app to be offline :) I can attest this from own experience. We had outages and maintenance where needed to take our server offline, the only thing that existing users have seen is a notification that they are working offline. You can try it by opening https://minutes.io/new/Meeting and turning of your wifi.

I hope that insights help a bit?

**Comment by talavishay** [comment]
thank you for the quick response..
hapi was the missing part for me..

**Comment by passcod** [comment]
Can this FAQ's text be updated to this answer? On the website it looks incomplete

**Comment by niallobrien** [comment]
@gr2m Can you elaborate as to how you're using Hapi alongside Hoodie exactly? Thanks.

**Comment by gr2m** [comment]
@niallobrien Hoodie is using hapi for all it’s server-side code. It’s pretty much a hapi server :)

**Comment by niallobrien** [comment]
@gr2m Ah, I wasn't aware. I assumed it was using Express as I'm almost certain Hoodie has been around longer than Hapi.

**Comment by gr2m** [comment]
yes, we migrated to Hapi at some point, but never looked back ever since. We are proud member of the [Hapi community](http://hapijs.com/community) :)
