### ISSUE TITLE
How to implement custom server side signUp logic?

### ISSUE THREAD

**Issue by msurdi** [hoodiehq/faq#143]
I'm using hoodie as a hapi plugin and I'm wondering if there is any recommended approach/suggestion to disable or modify the default server side implementation of the signUp process so that I can implement my own.

I think this is part of a more general question of how to replace any given server side part of hoodie when its default behaviour doesn't fit my needs anymore.

Thanks a lot for your help.

**Comment by gr2m** [comment]
hey @msurdi. A custom sign up logic is something we would love to add. See the `confirmation` option in `@hoodie/account-server`: https://github.com/hoodiehq/hoodie-account-server/tree/master/plugin#optionsconfirmation

At this point I’d remove the `email` value and just have it either true or false, then have custom plugins implement custom confirmation workflows for hoodie accounts, including email, sms, webhook callbacks from stripe etc.

But the `confirmation` option is not yet implemented :) At this point once a user account is created, a database for the user is created in `@hoodie/server`

https://github.com/hoodiehq/hoodie-server/blob/306347707a1a1c8bc463d4d463e2d8ae861344ce/index.js#L22-L47

So there are a few things that need to be done

1. add a way to https://github.com/hoodiehq/hoodie-account-server-api to have user accounts automatically confirmed, by adding a "confirmed" role and setting a `confirmedAt` timestamp. We probably want to implement hooks for that like we did in the client code: https://github.com/hoodiehq/hoodie-account-client#hooks
2. Once we have that, implement the `confirmation` option. Maybe rename it to `autoConfirm` so that it can be set to `false`.
3. Make sure that a user cannot sign in to their account if the account is unconfirmed
4. Only create a database once a user account is confirmed
5. Implement your custom server logic that confirms a user account as you need it.

I’d love to help you work trough that if you are interested. The code base is pretty decent and fun to contribute to, we put a lot of effort into that :) Let me know if you have any questions
