### ISSUE TITLE
How is Password Security handled in Hoodie?

### ISSUE THREAD

**Issue by lenareinhard** [hoodiehq/faq#31]
Passwords are handled via POST over SSL to a server where it gets hashed as pbkdf2. The password is never stored offline. 

Although Hoodie is offline-capable, this is why signing up new users only works when you are online.

**Comment by tomaszguzialek** [comment]
Signing-up new users works only online. What about login? The passwords are never stored offline, so the user is not able to authenticate himself. The user could actually use the application only when authenticated himself online and went offline (the cookie is then already stored offline). Do I understand it right?

**Comment by gr2m** [comment]
Yes. But two things I'd like to add:

1. You can use an app without signing in while being offline, then sign in later with `{moveData: true}` option, which will move all the data from the anonymous account to the authenticated one.
2. Technically, we could encrypt the data locally with a key when signing out, instead of removing it. Then you could sign in and retrieved the locally encrypted data, even when offline. See https://github.com/hoodiehq/hoodie.js/issues/397 for more information
